version = 1

test_patterns = ["**/__tests__/*"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "es-modules"
  environment = [
    "browser",
    "jest"
  ]
  plugins = ["vue"]
